gitmark/api/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from rest_framework.urlpatterns import format_suffix_patterns

from . import views

urlpatterns = [
    # url(r'^$', main_view.AdminIndexView.as_view()),
    # url(r'^admin/', include(admin.site.urls)),
    # url(r'^main/', include('main.urls', namespace='main')),
    # url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^repos/(?P<pk>[0-9]+)/stargazers/$', views.StargazersListView.as_view()),
    url(r'^users/(?P<pk>[0-9]+)/starred/$', views.UserStarredRepos.as_view()),
    url(r'^user/starred/$', views.UserStarredRepos.as_view()),
    url(r'^user/starred/(?P<pk>[0-9]+)/$', views.StarActivityView.as_view()),
]

urlpatterns = format_suffix_patterns(urlpatterns)

gitmark/gitmark/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from main import views as main_view, init

urlpatterns = [
    url(r'^$', main_view.AdminIndexView.as_view()),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^main/', include('main.urls', namespace='main')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^api/', include('api.urls', namespace='api')),
]

# GitMark Init
urlpatterns += [
    url(r'^init/$', init.GitMarkInitView.as_view(), name='init'),
]

urlpatterns += [
    url(r'^api-auth/', include('rest_framework.urls',
                               namespace='rest_framework')),
]

gitmark/main/urls.py
from django.conf.urls import patterns, url

from main import views, ajax, init

from django.contrib import admin
# admin.autodiscover()

urlpatterns = [
    # Examples:
    # url(r'^$', 'gitmark.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', views.AdminIndexView.as_view(), name='admin_index'),
    url(r'^enterprise/$', views.EnterpriseView.as_view(), name='enterprise'),
    url(r'^home/$', views.HomeView.as_view(), name='home'),
]



# admin urls
urlpatterns += [
    url(r'^repos/import/$', views.ImportRepoView.as_view(), name='admin_import_repo'),
    url(r'^repos/import/any/$', views.ImportRepoView.as_view(), {'starred':False}, name='admin_import_any_repo'),
    url(r'^repos/starred/$', views.StarredRepoView.as_view(), name='admin_starred_repo'),
    url(r'^collections/$', views.MyCollectionView.as_view(), name='my_collections'),
    url(r'^collections/(?P<pk>[0-9]+)/$', views.MyCollectionDetailView.as_view(), name='my_collection'),
    url(r'^collections/(?P<pk>[0-9]+)/modification/$', views.CollectionModify.as_view(), name='collection_modification'),
    url(r'^collections/(?P<pk>[0-9]+)/edit/$', views.MyCollectionEditView.as_view(), {'from_starred':True}, name='my_collection_edit_starred'),
    url(r'^collections/(?P<pk>[0-9]+)/edit/all/$', views.MyCollectionEditView.as_view(), {'from_starred':False}, name='my_collection_edit_all'),
    url(r'^collections/(?P<pk>[0-9]+)/edit/search/$', views.SearchRepos4Collection.as_view(), name='my_collection_edit_search'),
]

# ajax
urlpatterns += [
    url(r'^ajax/user/star-activity/(?P<pk>[0-9]+)/$', ajax.change_star_status, name='change_star_status'),
    url(r'^ajax/user/collections/$', ajax.list_user_collections, name='user_collection_list'),
    url(r'^ajax/user/repo/(?P<repo_id>[0-9]+)/collections/$', ajax.repo_collection_status, name='repo_collection_status'),
]

gitmark/templates/myadmin/collection.html
{% extends 'admin_base.html' %}
{% block main %}
{% load bootstrap3 %}

<div class="row">
    <div class="col-md-8 col-md-offset-1">
        <div class="row">
            <ol class="breadcrumb">
              <li><a href="{% url 'main:my_collections' %}">Collections</a></li>
              <li class="active">{{ cur_collection.name }}</li>
            </ol>
        </div>
        
        <div class="row">
            <div class="btn-group" role="group" aria-label="...">
              <button type="button" class="btn btn-primary"><a href="{% url 'main:my_collection_edit_starred' cur_collection.id %}"><i class="fa fa-pencil-square-o"></i> Edit</a></button>
              <button type="button" class="btn btn-primary"><a href="#"><i class="fa fa-trash"></i> Clear</a></button>
            </div>
        </div>
        <div class="row">
            {% for repo in repos %}
            <div class="col-md-9">
                <h3><a href="{{ repo.link }}" target="_blank" >{{ repo.full_name}}</a></h3>
                <p>{{ repo.desc}}</p>
                <p>
                    <span class="label label-default"><small>{{repo.language.name}}</small></span> &nbsp;
                    <i class="fa fa-star"></i> &nbsp;
                    <i class="fa fa-trash"></i>
                </p>
                <hr>
            </div>

            {% empty %}
            <div class="col-md-9">
                <br><br>
                <p>No collection yet</p>
            </div>
            
            {% endfor %}
        </div>
        {% bootstrap_pagination repos %}
    </div>
    <div class="col-md-3">
        <h4>Collections</h4><hr>
        <ul class="list-group">
        {% for collection in collections %}
          {% if cur_collection.id == collection.id %}
                <a href="{% url 'main:my_collection' collection.id %}" class="list-group-item no-border-group-list active">{{ collection.name }} 
                <small><span class="glyphicon glyphicon-remove small rm-filter" aria-hidden="true"></span></small>
                </a>
            {% else %}
                <a href="{% url 'main:my_collection' collection.id %}" class="list-group-item no-border-group-list ">{{ collection.name }}</a>
            {% endif %}
        {% endfor %}
        </ul>

    </div>
</div>
{% endblock %}



{% block js %}
<script type="text/javascript">
    $('.rm-filter').on('click', function (event) {
        location.href = "{% url 'main:my_collections' %}";
        return false;
      });

</script>
{% endblock %}

gitmark/templates/myadmin/collection_edit.html
{% extends 'admin_base.html' %}

{% block main %}
{% load bootstrap3 %}

<ol class="breadcrumb">
  <li><a href="{% url 'main:my_collections' %}">Collections</a></li>
  <li><a href="{% url 'main:my_collection' collection.id %}">{{ collection.name }}</a></li>
  <li class="active">edit</li>
</ol>

<ul class="nav nav-tabs">
  <li role="presentation" {% if starred %} class="active" {% endif %}><a href="{% url 'main:my_collection_edit_starred' collection.id %}">Starred Repos</a></li>
  <li role="presentation" {% if all %} class="active" {% endif %}><a href="{% url 'main:my_collection_edit_all' collection.id %}">All Repos</a></li>
  <li role="presentation"><a href="{% url 'main:my_collection_edit_search' collection.id %}">Search</a></li>
  <li role="presentation"><a href="{% url 'main:my_collection' collection.id %}"><i class="fa fa-history"></i></a></li>
</ul>
<div class="row">
  <br>
  <div class="col-md-8">
    <form method="POST">
    {% csrf_token %}
      {% for repo in repos %}
        <div class="col-md-6">
          <div class="form-group">
            <label>
              <input type="checkbox" name='repos' value={{ repo.id }} > {{ repo.full_name }} <a href="{{ repo.link }}"><i class="fa fa-github"></i></a>
            </label>
              
            
            <p><small>{{ repo.desc }}</small></p>
            <p><span class="label label-default"><small>{{repo.language.name}}</small></span></p>
            <hr>
          </div>
        </div>
      {% endfor %}

      <div class="col-md-12">
        <button class="btn btn-default">Submit</button>
      </div>

      <div class="col-md-12">
        {% bootstrap_pagination repos url=url_parm %}
      </div>
  
    </form>
  </div>
  <div class="col-md-4">
    <h4>Languagues</h4><hr>
    <div class="list-group">
        {% for language in languages %}
            {% if language_id == language.id %}
                <a href="?language={{language.id}}" class="list-group-item no-border-group-list active">{{ language.name }} 
                <small><span class="glyphicon glyphicon-remove small rm-filter" aria-hidden="true"></span></small></a>
            {% else %}
                <a href="?language={{language.id}}" class="list-group-item no-border-group-list ">{{ language.name }}</a>
            {% endif %}
        {% endfor %}
    </div>
  </div>
</div>

{% endblock %}


{% block js %}
<script type="text/javascript">
  $('.rm-filter').on('click', function (event) {
      location.href = ".";
      return false;
    });
</script>
{% endblock %}

gitmark/templates/myadmin/collection_search_repo.html
{% extends 'admin_base.html' %}

{% block main %}
{% load bootstrap3 %}

<ol class="breadcrumb">
  <li><a href="{% url 'main:my_collections' %}">Collections</a></li>
  <li><a href="{% url 'main:my_collection' collection.id %}">{{ collection.name }}</a></li>
  <li class="active">edit</li>
</ol>

<ul class="nav nav-tabs">
  <li role="presentation"><a href="{% url 'main:my_collection_edit_starred' collection.id %}">Starred Repos</a></li>
  <li role="presentation"><a href="{% url 'main:my_collection_edit_all' collection.id %}">All Repos</a></li>
  <li role="presentation" class="active"><a href="{% url 'main:my_collection_edit_search' collection.id %}">Search</a></li>
  <li role="presentation"><a href="{% url 'main:my_collection' collection.id %}"><i class="fa fa-history"></i></a></li>
</ul>
<div class="row">
  <br>
  <div class="col-md-10 col-md-offset-1">
    <div class="col-md-12">
      <form>
        <div class="form-group">
          <input type="text" class="form-control" name="keyword" placeholder="keyword" {% if keyword %} value="{{ keyword }}" {% endif %}>
          
        </div>
        

        <div class="form-inline">
          <div class="radio">
            <label>
              <input type="radio" name="flag" value="all" checked >
              All
            </label>
          </div>
          <div class="radio">
            <label>
              <input type="radio" name="flag" value="repo" {% if flag == 'repo' %} checked {% endif %} >
              Repo
            </label>
          </div>
          <div class="radio">
            <label>
              <input type="radio" name="flag" value="description" {% if flag == 'description' %} checked {% endif %} >
              Description
            </label>
          </div>
          <div class="radio">
            <label>
              <input type="radio" name="flag" value="author" {% if flag == 'author' %} checked {% endif %}>
              Author
            </label>
          </div>
        </div>

        <br>
        <div class="form-group">
          <button type="submit" class="btn btn-default">Search</button>
        </div>


      </form>
      <hr>
    </div>
    <form method="POST">
    {% csrf_token %}
      {% for repo in repos %}
        <div class="col-md-6">
          <div class="form-group">
            <label>
              <input type="checkbox" name='repos' value={{ repo.id }} > {{ repo.full_name }} <a href="{{ repo.link }}"><i class="fa fa-github"></i></a>
            </label>
              
            
            <p><small>{{ repo.desc }}</small></p>
            <p><span class="label label-default"><small>{{repo.language.name}}</small></span></p>
            <hr>
          </div>
        </div>

      {% empty %}
        <div class='col-md-12'>
          No repo found yet！
        </div>
      {% endfor %}

      {% if repos %}
      <div class="col-md-12">
        <button class="btn btn-default">Submit</button>
      </div>
      {% endif %}

    </form>
    {% if repos %}
    <div class="col-md-12">
        {% bootstrap_pagination repos url=url_parm %}
    </div>
    {% endif %}
  </div>
  
</div>

{% endblock %}


{% block js %}

{% endblock %}

gitmark/templates/myadmin/collections.html
{% extends 'admin_base.html' %}
{% block main %}
{% load bootstrap3 %}

<div class="row">
    <div class="col-md-10 col-md-offset-1">

    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#add-collection">
      Add Collection 
    </button>

    <!-- Modal -->
    <div class="modal fade" id="add-collection" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">Add New Collection</h4>
          </div>
          <form method="POST">
          {% csrf_token %}
              <div class="modal-body">
                {% bootstrap_form form %}
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary">Save</button>
              </div>
          </form>
        </div>
      </div>
    </div>

    <table class="table">
        <thead>
            <th>No.</th>
            <th>Name</th>
            <th>Description</th>
            <th>Create Time</th>
            <th>Update Time</th>
            <th>Actions</th>
        </thead>
        <tbody>
        {% for collection in collections %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td><a href="{% url 'main:my_collection' collection.id %}">{{ collection.name }}</a></td>
            <td>{{ collection.description | default:"No description yet" }}</td>
            <td>{{ collection.create_date }}</td>
            <td>{{ collection.last_update }}</td>
            <td>
                <a href="{% url 'main:collection_modification' collection.id %}"><i class="fa fa-pencil-square-o"></i></a>
                <a href="#"><i class="fa fa-trash"></i></a>
            </td>
        </tr>
            
        {% endfor %}
        </tbody>
    </table>

    </div>
</div>
{% endblock %}


{% block js %}
<script type="text/javascript">
    $('#add-collection').on('shown.bs.modal', function () {
  $('#myInput').focus()
})
</script>
{% endblock %}

gitmark/templates/myadmin/import_repo.html
{% extends 'admin_base.html' %}
{% block main %}
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        {% if starred %}
        <h3>Import My Starred Repos</h3>
        <form method="POST">
            {% csrf_token %}
            <button type="submit" class="btn btn-primary" name="import_mine" value="true">Import from <i class="fa fa-github"></i></button>
        </form>

        <hr>

        {% endif %}

        <h3>Import From Other's Starred Repos </h3>
        <form method="POST">
            {% csrf_token %}
            <div class="form-group">
                <!-- <label for="InputGitHubUsername">Import From Other's Starred Repos </label> -->
                <input type="text" class="form-control" id="InputGitHubUsername" placeholder="GitHub username" name="github_username">
            </div>
            {% if starred %}
                <button type="submit" class="btn btn-primary">Import</button>
            {% else %}
                <button type="submit" class="btn btn-success">Import To GitMark</button>
            {% endif %}
        </form>
    </div>
</div>
{% endblock %}


{% block js %}
{% endblock %}

gitmark/templates/myadmin/index.html
{% extends 'admin_base.html' %}
{% block main %}
<div class="row">
    <div class="col-md-3 col-md-offset-1">
        <h3>User Account</h3><hr>
        <img src="{{ request.user.account.avatar }}" width="80%" class="img-rounded">
        <h4>Username</h4>
        {{ request.user.username }}
        <hr>

        <h4>GitHub Account</h4>
        <form method="POST">
        {% csrf_token %}
            <p>
            {% if request.user.account.github_username %}
                <i class="fa fa-github fa-lg"> </i> <a href="#">{{ request.user.account.github_username }}</a> &nbsp;| 
                <button type="submit" class="btn btn-link" name="rm_github" value='true'>  <i class="fa fa-trash-o"></i></button>
            {% else %}
                <button type="submit" class="btn btn-success" name="link_github" value='true'> Link to <i class="fa fa-github"></i></button>
            {% endif %}
            </p>
        </form>
        <hr>

        <h4>Social Network</h4>
            {% if request.user.account.github %}
                <a href='{{ request.user.account.github }}'><i class="fa fa-github fa-lg"></i></a> &nbsp;
            {% endif %}

            {% if request.user.account.twitter %}
                <a href='{{ request.user.account.twitter }}'><i class="fa fa-twitter fa-lg"></i></a> &nbsp;
            {% endif %}

            {% if request.user.account.weibo %}
                <a href='{{ request.user.account.weibo }}'><i class="fa fa-weibo fa-lg"></i></a>
            {% endif %}
        <hr>

        <h4>Homepage</h4>
            {% if request.user.account.homepage %}
            <a href="{{ request.user.account.homepage }}"><i class="fa fa-home fa-lg"></i></a> {{ request.user.account.homepage }}
            {% endif %}
        <hr>

        <div class="row" style="text-align:center">
            <div class='col-md-3'>
                <p class="lead">2048</p>
                <small>following</small>
            </div>
            <div class='col-md-3'>
                <p class="lead">2048</p>
                <small>follower</small>
            </div>
            <div class='col-md-3'>
                <a href="{% url 'main:admin_starred_repo' %}"><p class="lead">{{ starred_count }}</p></a>
                <small>starred</small>
            </div>
            <div class='col-md-3'>
                <a href="{% url 'main:my_collections' %}"><p class="lead">{{ collection_count }}</p></a>
                <small>collection</small>
            </div>
        </div>
        
    </div>
    <div class="col-md-4">
        <h3>Recently Starred Repos</h3><hr>
        {% for starred_repo in starred_repos %}
            <div class="row">
                <div class="col-md-12">
                    <p class="lead"><a href="{{ starred_repo.link }}">{{ starred_repo.full_name}}</a></p>
                    <p>{{ starred_repo.desc}}</p>
                    <!-- <p class="grey-text"><small>Language: {{starred_repo.language.name}}</small> </p> -->
                    <p><span class="label label-default"><small>{{ starred_repo.language.name }}</small></span></p>
                </div>
            </div>
        {% if not forloop.last%}<hr>{% endif %}

        {% endfor %}

        {% if starred_count > 5%}<a href="#">See All</a>{% endif %}
    </div>
    <div class="col-md-3">
        <h3>Collections</h3><hr>
        {% for collection in collections %}
            <div class="row">
                <div class="col-md-12">
                    <p class="lead"><a href="#">{{ collection.name}}</a></p>
                    <p>{{ collection.description}}</p>
                </div>
            </div>
        {% if not forloop.last%}<hr>{% endif %}

        {% endfor %}

        {% if collection_count > 5%}<a href="#">See All</a>{% endif %}
    </div>
</div>
{% endblock %}


{% block js %}
{% endblock %}

gitmark/templates/myadmin/simple_form.html
{% extends "admin_base.html" %}

{% block title %}{{ title }}{% endblock %}

{% load static %}


{% block main %}
{% load bootstrap3 %}
<div class="row">
    <div class="col-xs-6 col-sm-3"></div>
    <div class="col-xs-6 col-sm-6">
    <h3>{{ heading }}</h3>
    <hr>
        <form method="POST" action="">
        {% csrf_token %}
            {% bootstrap_form form %}
            <button type="submit" class="btn btn-primary" name="submit">
            {% if btn_name %}
                {{ btn_name }}
            {% else %}
                submit
            {% endif %}
            </button>
        </form>
    </div>
    <div class="col-xs-6 col-sm-3"></div>
</div>

{% endblock %}

gitmark/templates/myadmin/starred_repo.html
{% extends 'admin_base.html' %}
{% block main %}
{% load bootstrap3 %}

<div class="row">
    <div class="col-md-7 col-md-offset-1">
    {% for starred_repo in starred_repos %}
    <div class="row">
        <div class="col-md-12">
            <h3><a href="{{ starred_repo.link }}">{{ starred_repo.full_name}}</a></h3>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8">
            <p>{{ starred_repo.desc}}</p>
            <!-- <p class="grey-text"><small>Language: {{starred_repo.language.name}}</small> </p> -->
            <p><span class="label label-default"><small>{{ starred_repo.language.name }}</small></span></p>
        </div>
        <div class="col-md-4">
            <div class="btn-group" role="group" aria-label="...">
              <button type="button" class="btn btn-default btn-sm btn-star" data-url="{% url 'main:change_star_status' starred_repo.id %}">
               <i class="fa fa-star"></i> unstar</button>

              <div class="btn-group" role="group">
                <button type="button" class="btn btn-default btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Collections
                  <span class="caret"></span>
                </button>
                <ul class="dropdown-menu">
                  <li><input type="checkbox"> collection 1</li>
                  <li><input type="checkbox"> collection 2</li>
                </ul>
              </div>
            </div>
        </div>
    </div>

        <hr>
    {% endfor %}

    {% bootstrap_pagination starred_repos url=url_parm %}

    </div>
    <div class="col-md-3">
        <h4>Filter by Language <i class="fa fa-filter"></i> </h4>
        <hr>
        <div class="list-group">
            {% for language in languages %}
                {% if language_id == language.language %}
                    <a href="{% url 'main:admin_starred_repo' %}?language={{language.language}}" class="list-group-item no-border-group-list active">{{ language.name }} 
                    <small><span class="glyphicon glyphicon-remove small rm-filter" aria-hidden="true"></span></small>
                    <span class="badge">&nbsp;{{language.num_repo}}&nbsp;</span></a>
                {% else %}
                    <a href="{% url 'main:admin_starred_repo' %}?language={{language.language}}" class="list-group-item no-border-group-list ">{{ language.name }} 
                    <span class="badge">&nbsp; {{language.num_repo}} &nbsp;</span></a>
                {% endif %}
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}


{% block js %}
<script type="text/javascript">
    $('.rm-filter').on('click', function (event) {
        location.href = "{% url 'main:admin_starred_repo' %}";
        return false;
      });
    $(function () {
      $('[data-toggle="tooltip"]').tooltip()
    });

    // star/unstar a repo
    $('.btn-star').on('click', function(event){
        // alert($(this).data('id'));
        var url = $(this).data('url');
        // alert($(this).text())
        btn = $(this);

        $.ajax({
            url: url,
            type: 'GET',
            // data: {'name': result},
            success: function(result){
                // location.reload();
                // alert(url);
                console.log(result);
                var val = ''
                if(result == 'unstarred'){
                    val = '<i class="fa fa-star-o"></i> star';
                    
                }else{
                    val = '<i class="fa fa-star"></i> unstar';
                }
                // $(this).text(val);
                // console.log(val);
                btn.html(val)
            }
          })
    });
</script>
{% endblock %}