gitmark/accounts/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url
from . import views, github_auth

# urlpatterns = patterns('',
#     # Examples:
#     # url(r'^$', 'blog.views.home', name='home'),
#     # url(r'^blog/', include('blog.urls')),

#     url(r'^login/$', views.LoginView.as_view(), name='login'),
#     url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
#     url(r'^register/$', views.RegisterView.as_view(), name='register'),
#     url(r'^profile/$', views.ProfileView.as_view(), name='profile'),
#     url(r'^profile/password/$', views.ChangePasswordView.as_view(), name='change_password'),
#     # url(r'^users/$', views.UsersView.as_view(), name='users'),
#     # url(r'^users/(?P<pk>(-)?[0-9]+)/$', views.UserView.as_view(), name='user'),
#     # url(r'^users/(?P<pk>(-)?[0-9]+)/edit/$', views.UserEditView.as_view(), name='user_edit'),
#     # url(r'^groups/(?P<group_id>[0-9]+)/users/$', views.UsersView.as_view(), name='group_users'),
#     # url(r'^groups/$', views.GroupsView.as_view(), name='groups'),
#     # url(r'^groups/(?P<pk>(-)?[0-9]+)/$', views.GroupView.as_view(), name='group'),
# )

urlpatterns = [
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^register/$', views.RegisterView.as_view(), name='register'),
    url(r'^profile/$', views.ProfileView.as_view(), name='profile'),
    url(r'^profile/password/$', views.ChangePasswordView.as_view(), name='change_password'),
    ]

#GitHub Auth
urlpatterns +=[
    url(r'^github/auth/$', github_auth.github_auth, name='github_auth'),
    url(r'^github/callback/$', github_auth.github_callback, name='github_callback'),
]

gitmark/api/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from rest_framework.urlpatterns import format_suffix_patterns

from . import views

urlpatterns = [
    # url(r'^$', main_view.AdminIndexView.as_view()),
    # url(r'^admin/', include(admin.site.urls)),
    # url(r'^main/', include('main.urls', namespace='main')),
    # url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^repos/(?P<pk>[0-9]+)/stargazers/$', views.StargazersListView.as_view()),
    url(r'^users/(?P<pk>[0-9]+)/starred/$', views.UserStarredRepos.as_view()),
    url(r'^user/starred/$', views.UserStarredRepos.as_view()),
    url(r'^user/starred/(?P<pk>[0-9]+)/$', views.StarActivityView.as_view()),
]

urlpatterns = format_suffix_patterns(urlpatterns)

gitmark/gitmark/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from main import views as main_view, init

urlpatterns = [
    url(r'^$', main_view.AdminIndexView.as_view()),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^main/', include('main.urls', namespace='main')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^api/', include('api.urls', namespace='api')),
]

# GitMark Init
urlpatterns += [
    url(r'^init/$', init.GitMarkInitView.as_view(), name='init'),
]

urlpatterns += [
    url(r'^api-auth/', include('rest_framework.urls',
                               namespace='rest_framework')),
]

gitmark/main/urls.py
from django.conf.urls import patterns, url

from main import views, ajax, init

from django.contrib import admin
# admin.autodiscover()

urlpatterns = [
    # Examples:
    # url(r'^$', 'gitmark.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', views.AdminIndexView.as_view(), name='admin_index'),
    url(r'^enterprise/$', views.EnterpriseView.as_view(), name='enterprise'),
    url(r'^home/$', views.HomeView.as_view(), name='home'),
]



# admin urls
urlpatterns += [
    url(r'^repos/import/$', views.ImportRepoView.as_view(), name='admin_import_repo'),
    url(r'^repos/import/any/$', views.ImportRepoView.as_view(), {'starred':False}, name='admin_import_any_repo'),
    url(r'^repos/starred/$', views.StarredRepoView.as_view(), name='admin_starred_repo'),
    url(r'^collections/$', views.MyCollectionView.as_view(), name='my_collections'),
    url(r'^collections/(?P<pk>[0-9]+)/$', views.MyCollectionDetailView.as_view(), name='my_collection'),
    url(r'^collections/(?P<pk>[0-9]+)/modification/$', views.CollectionModify.as_view(), name='collection_modification'),
    url(r'^collections/(?P<pk>[0-9]+)/edit/$', views.MyCollectionEditView.as_view(), {'from_starred':True}, name='my_collection_edit_starred'),
    url(r'^collections/(?P<pk>[0-9]+)/edit/all/$', views.MyCollectionEditView.as_view(), {'from_starred':False}, name='my_collection_edit_all'),
    url(r'^collections/(?P<pk>[0-9]+)/edit/search/$', views.SearchRepos4Collection.as_view(), name='my_collection_edit_search'),
]

# ajax
urlpatterns += [
    url(r'^ajax/user/star-activity/(?P<pk>[0-9]+)/$', ajax.change_star_status, name='change_star_status'),
    url(r'^ajax/user/collections/$', ajax.list_user_collections, name='user_collection_list'),
    url(r'^ajax/user/repo/(?P<repo_id>[0-9]+)/collections/$', ajax.repo_collection_status, name='repo_collection_status'),
]

gitmark/templates/admin_base.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}GitMark{% endblock %}</title>

    {% load static %}
    <!-- Bootstrap Core CSS -->
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'img/favicon-96x96.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/favicon-16x16.png' %}">

    <link href="http://cdn.staticfile.org/twitter-bootstrap/3.3.1/css/bootstrap.min.css" rel="stylesheet">
    <link href="http://cdn.staticfile.org/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="{% static 'css/gitmark.css' %} " rel="stylesheet">
    {# Load the tag library #}
    {% load bootstrap3 %}


    
    {# Display django.contrib.messages as Bootstrap alerts #}
    {% bootstrap_messages FIXTHIS %}

    <!-- Custom CSS -->
    <!-- <link href="{% static 'css/clean-blog.min.css' %} " rel="stylesheet"> -->
    {% block css %}{% endblock %}

    <!-- Custom Fonts -->
    <!-- <link href="http://libs.useso.com/js/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css"> -->

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">GitMark <i class="fa fa-user"></i></a>
        </div>

        {% if request.user.is_authenticated %}
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="_active"><a href="{% url 'main:admin_index' %}"><i class="fa fa-home"></i> Home <span class="sr-only">(current)</span></a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-code"></i> Repositories <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="{% url 'main:admin_starred_repo' %}"><i class="fa fa-star"></i> Starred Repos</a></li>
                <li><a href="{% url 'main:admin_import_repo' %}"><i class="fa fa-download"></i> Import Starred Repos</a></li>
                <li class="divider"></li>
                <li><a href="#"><i class="fa fa-list-ul"></i> All Repos</a></li>
                <li><a href="{% url 'main:admin_import_any_repo' %}"><i class="fa fa-download"></i> Import Repos</a></li>
                <li><a href="#"><i class="fa fa-pencil-square-o"></i> Edit Repos</a></li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-cubes"></i> Collection <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="{% url 'main:my_collections' %}"><i class="fa fa-star"></i> My Collections</a></li>
                <li><a href="#"><i class="fa fa-eye"></i> Following Collections</a></li>
                <!-- <li><a href="#">Something else here</a></li> -->
                <li class="divider"></li>
                <li><a href="#"><i class="fa fa-pencil-square-o"></i> Edit Collections</a></li>
              </ul>
            </li>
            <li><a href="#"><i class="fa fa-folder-open"></i> Explore</a></li>
            <!-- <li><a href="#"><i class="fa fa-cubes"></i> Collection</a></li> -->
            
          </ul>
          
          <ul class="nav navbar-nav navbar-right">
          
            <form class="navbar-form navbar-left" role="search" method="get">
                <div class="form-group">
                  <input type="text" class="form-control" placeholder="Search" name="key">
                </div>
                <button type="submit" class="btn btn-default">Submit</button>
            </form>
          
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">{{ request.user.username }} <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="{% url 'accounts:profile' %}"><i class="fa fa-cogs"></i> Settings</a></li>
                <!-- <li><a href="#">Another action</a></li> -->
                <!-- <li><a href="#">Something else here</a></li> -->
                <li class="divider"></li>
                <li><a href="{% url 'accounts:logout' %}"><i class="fa fa-sign-out"></i> Exit</a></li>
              </ul>
            </li>
          </ul>

        </div><!-- /.navbar-collapse -->
        {% else %}
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'accounts:login' %}"><i class="fa fa-sign-in"></i> Login</a></li>
            <li><a href="{% url 'accounts:register' %}"><i class="fa fa-plug"></i> Register</a></li>
          </ul>
        </div>
        {% endif %}
      </div><!-- /.container-fluid -->
    </nav>

    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    {%block header %}{% endblock %}

    <div class="container">
        <!-- Main Content -->

        
        {%block main %}{% endblock %}

    </div>

    <hr>

    
    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <ul class="list-inline text-center">
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <p class="copyright text-muted text-center">Copyright &copy; GitMark 2015</p>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="http://cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="http://cdn.staticfile.org/twitter-bootstrap/3.3.1/js/bootstrap.min.js"></script>
    <script src="http://cdn.staticfile.org/bootbox.js/4.3.0/bootbox.min.js"></script>

    {% if request.user.is_authenticated %}
        <script>(function(i,s,o,g,r,a,m){i["DaoVoiceObject"]=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)})(window,document,"script","//widget.daovoice.io/widget/f9b57d5e.js","daovoice");</script>
        <script>
          daovoice('init', {
            app_id: "f9b57d5e",
            user_id: "{{ request.user.id }}", // 必填: 该用户在您系统上的唯一ID
            email: "{{ request.user.email }}", // 选填:  该用户在您系统上的主邮箱
            name: "{{ request.user.username }}", // 选填: 用户名
            signed_up: {{ request.user.date_joined|date:"U" }} // 选填: 用户的注册时间，用Unix时间戳表示
          });
          daovoice('update');
        </script>
    {% else %}
        <script>(function(i,s,o,g,r,a,m){i["DaoVoiceObject"]=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)})(window,document,"script","//widget.daovoice.io/widget/f9b57d5e.js","daovoice");</script>
        <script>
          daovoice('init', {
            app_id: "f9b57d5e",
          });
          daovoice('update');
        </script>
    {% endif %}
    

    <!-- Custom Theme JavaScript -->
    {% block js %}
    {% endblock %}
    

</body>

</html>

gitmark/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Git Mark</title>

    <!-- Bootstrap -->
    <!-- Latest compiled and minified CSS -->
    <!-- <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css"> -->
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- Optional theme -->
    <!-- <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css"> -->

    <!-- Add custom CSS here -->
    <link rel="stylesheet" href="{% static 'css/gitmark.css' %}" >

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <nav class="navbar navbar-default" role="navigation">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Git Mark</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li>
              <form class="navbar-form navbar-right" role="search">
                <div class="form-group">
                  <input type="text" class="form-control" placeholder="Search">
                </div>
                <!-- <button type="submit" class="btn btn-default">Submit</button> -->
              </form>
            </li>
              <li class="active"><a href="#">Explore</a></li>
              <li><a href="#">Collection</a></li>
          </ul>

          <ul class="nav navbar-nav navbar-right">
            <!-- <li><a href="#">hi,</a></li> -->
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">admin <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">Home</a></li>
                <li><a href="#">Collection</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li><a href="#">settings</a></li>
              </ul>
            </li>
            <li><a href="#">logout</a></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

  <div id="wrapper">
    {% block main %}{% endblock %}
    <footer>
      <div class="row">
        <div class="col-lg-12">
          <p>Copyright &copy; Company 2013</p>
        </div>
      </div>
    </footer>
  </div>


    <script src="{% static 'js/jquery-1.10.2.js'%}"></script>
    <script src="{% static 'js/bootstrap.min.js'%}"></script>
    {% block js %}{% endblock %}

  </body>
</html>